services:
  api-server:
    container_name: api-server
    build:
      context: ./
      dockerfile: ./packages/api-server/Dockerfile.prod
    init: true
    volumes:
      - type: bind
        source: ./libs
        target: /usr/libs
    networks:
      - production
    ports:
      - 3000:3000
    restart: unless-stopped

  client-nginx:
    container_name: client-nginx
    build: 
      context: ./
      dockerfile: ./packages/client/Dockerfile.nginx
    init: true
    volumes:
      - type: bind
        source: ./packages/client/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - production
    ports:
      - 80:8080

networks:
  production: